export const GRID_COLUMNS = 7;
export const GRID_ROWS = 6;
export const MIN_CLUSTER_SIZE = 5;
export const WILD_SYMBOL_ID = "WILD";
export const PAYTABLE_CAP_CLUSTER_SIZE = 12;
export const PAYTABLE_CAP_MULTIPLIER = 10000;
export const PAYTABLE_CURVE_EXPONENT = 6;

export const SLOT_SYMBOLS = [
  {
    id: "n1",
    label: "CSS Shield",
    kind: "premium",
    renderType: "asset",
    assetPath: "/slots/assets/n1.svg",
    weight: 7,
    payoutTier: 8,
    basePayoutMultiplier: 1,
  },
  {
    id: "n2",
    label: "Chip",
    kind: "premium",
    renderType: "asset",
    assetPath: "/slots/assets/n2.webp",
    weight: 10,
    payoutTier: 7,
    basePayoutMultiplier: 0.66,
  },
  {
    id: "n3",
    label: "Snake",
    kind: "premium",
    renderType: "asset",
    assetPath: "/slots/assets/n3.webp",
    weight: 11,
    payoutTier: 6,
    basePayoutMultiplier: 0.51,
  },
  {
    id: "n4",
    label: "CPP",
    kind: "premium",
    renderType: "asset",
    assetPath: "/slots/assets/n4.png",
    weight: 10,
    payoutTier: 5,
    basePayoutMultiplier: 0.41,
  },
  {
    id: "n5",
    label: "Python",
    kind: "premium",
    renderType: "asset",
    assetPath: "/slots/assets/n5.png",
    weight: 9,
    payoutTier: 4,
    basePayoutMultiplier: 0.33,
  },
  {
    id: "n6",
    label: "OpenClaw",
    kind: "premium",
    renderType: "asset",
    assetPath: "/slots/assets/n6.webp",
    weight: 8,
    payoutTier: 3,
    basePayoutMultiplier: 0.27,
  },
  {
    id: "A",
    label: "A",
    kind: "basic",
    renderType: "text",
    weight: 16,
    payoutTier: 2,
    basePayoutMultiplier: 0.19,
  },
  {
    id: "K",
    label: "K",
    kind: "basic",
    renderType: "text",
    weight: 15,
    payoutTier: 1,
    basePayoutMultiplier: 0.14,
  },
  {
    id: "Q",
    label: "Q",
    kind: "basic",
    renderType: "text",
    weight: 14,
    payoutTier: 0.8,
    basePayoutMultiplier: 0.1,
  },
  {
    id: "J",
    label: "J",
    kind: "basic",
    renderType: "text",
    weight: 13,
    payoutTier: 0.6,
    basePayoutMultiplier: 0.06,
  },
  {
    id: "WILD",
    label: "WILD",
    kind: "special",
    renderType: "asset",
    assetPath: "/slots/assets/WILD.svg",
    weight: 2.5,
    payoutTier: 0,
  },
];
